# Funding

You can support this project through the following platforms:

## GitHub Sponsors
You can support me on GitHub Sponsors:

- [w33bvGL](https://github.com/sponsors/w33bvGL)

## Other Platforms

Feel free to explore other ways to support the project:

- Patreon: (Insert your Patreon username here)
- Open Collective: (Insert your Open Collective username here)
- Ko-fi: (Insert your Ko-fi username here)
- Tidelift: (Insert Tidelift username here)
- Community Bridge: (Insert Community Bridge project-name here)
- Liberapay: (Insert Liberapay username here)
- IssueHunt: (Insert IssueHunt username here)
- LFX Crowdfunding: (Insert LFX Crowdfunding project-name here)
- Polar: (Insert Polar username here)
- Buy Me a Coffee: (Insert Buy Me a Coffee username here)
- thanks.dev: (Insert thanks.dev username here)
- Custom links: ['link1', 'link2']
